version: '3'

services:
  redis-master:
    image: redis:7.2.4
    container_name: redis-master
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-master-data:/data
    networks:
      - redis-net

  redis-replica-1:
    image: redis:7.2.4
    container_name: redis-replica-1
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes", "--replicaof", "redis-master", "6379"]
    volumes:
      - redis-replica-1-data:/data
    networks:
      - redis-net

  redis-replica-2:
    image: redis:7.2.4
    container_name: redis-replica-2
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "yes", "--replicaof", "redis-master", "6379"]
    volumes:
      - redis-replica-2-data:/data
    networks:
      - redis-net

volumes:
  redis-master-data:
  redis-replica-1-data:
  redis-replica-2-data:

networks:
  redis-net:
    driver: bridge